name: Build and Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main


jobs:

  macos-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-latest ]
        java: [ '11', '15', '17' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: x64
          java-package: jdk+fx
          cache: 'maven'

      - name: Build/test code with Maven
        run: |
          mvn --no-transfer-progress --batch-mode --file pom.xml install
          # mvn --no-transfer-progress --batch-mode --file pom.xml install -Dmaven.test.skip=true
          # mvn --no-transfer-progress --batch-mode --file audioplayer4j-complete/pom.xml install -Dtest=TestAudioPlayer#repeatedTestTimeForFile,TestAudioPlayer#lineFlushTest

      - name: Upload CodeCov Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.os == 'macos-10.15' && matrix.java == '11'


  windows-build:

    runs-on: windows-2019
    strategy:
      matrix:
        java: [ '11', '15', '17' ]

    steps:
      - name: Install Scream (Virtual Audio Device)
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.8/Scream3.8.zip -OutFile Scream3.8.zip
          Expand-Archive -Path Scream3.8.zip -DestinationPath Scream
          Import-Certificate -FilePath Scream\Install\driver\x64\Scream.cat -CertStoreLocation Cert:\LocalMachine\TrustedPublisher
          Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream

      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk+fx
          cache: 'maven'

      - name: Build/test code with Maven
        run: mvn --no-transfer-progress --batch-mode --file pom.xml install


  linux-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        java: [ '11', '15', '17' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Audio
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pulseaudio jackd2 alsa-utils dbus-x11

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk+fx
          cache: 'maven'

      - name: Build/test code with Maven
        run: |
          xvfb-run -a mvn --no-transfer-progress --batch-mode --file pom.xml install
          # xvfb-run -a mvn --no-transfer-progress --batch-mode --file pom.xml install -Dmaven.test.skip=true
          # xvfb-run -a mvn --no-transfer-progress --batch-mode --file audioplayer4j-complete/pom.xml install -Dtest=TestAudioPlayer#repeatedTestTimeForFileWhilePlaying,TestAudioPlayer#lineFlushTest
