name: Build and Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main


jobs:

  macos-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-latest ]
        java: [ 11, 15, 17 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: x64
          java-package: jdk+fx
          cache: 'maven'

      - name: Build/test code with Maven
        run: mvn -B install --file pom.xml

      - name: Upload CodeCov Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.os == 'macos-10.15' && matrix.java == 9


  windows-build:

    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x64, x86]
        java: [ 11, 15, 17 ]
        include:
          - arch: x64
            sys: mingw64
            env: x86_64
          - arch: x86
            sys: mingw32
            env: i686
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: mingw-w64-${{ matrix.env }}-toolchain
          path-type: inherit

      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk+fx
          cache: 'maven'

      - name: Build/test code with Maven
        run: |
          which mvn
          mvn -B install --file pom.xml


  linux-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest ]
        java: [ 11, 15, 17 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk+fx
          cache: 'maven'

      - name: Build/test code with Maven
        run: mvn -B install --file pom.xml
